### ISSUE TITLE
Linking errors

### ISSUE THREAD

**Issue by Joringer** [96boards/96BoardsGPIO#14]
Hello, I don't know if this is really the place to ask this but I have searched elsewhere and didn't find anything, sorry if this is not to be posted here.

I am trying to build the example blink.c, have installed 96boards and its dependencies (via the autoreconf -i option), but it won't compile the script.

I am using this command : g++ blink.c -o Blink -lsoc -l96BoardsGPIO

I am getting these errors : 
`main.c:(.text+0x8c4): undefined reference to`gpio_id(char const_)'
main.c:(.text+0x8dc): undefined reference to `gpio_open(unsigned int, char const_)'
main.c:(.text+0x904): undefined reference to `digitalWrite(unsigned int, unsigned int)'
main.c:(.text+0x91c): undefined reference to`digitalWrite(unsigned int, unsigned int)'
collect2: error: ld returned 1 exit status
`

Would you have any idea how to correct this error please ? Sorry if this is a newbie question

Cheers, Pierre

**Comment by zoltan-ongithub** [comment]
This may do the magic:

`gcc blink.c -o Blink -lsoc -l96BoardsGPIO
`
note: g++ -> gcc

or just call **make**.

**Comment by Joringer** [comment]
This worked, thank you very much :). I kinda feel bad for not thinking about trying that though.
