### ISSUE TITLE
License.

### ISSUE THREAD

**Issue by pbostley** [96boards/96BoardsGPIO#2]
You have an ambiguous mix of GPL (COPYING) and LGPL (LICENSE, and other file headers) in the archive.  Which is it?

**Comment by dmandala** [comment]
LGPL 2.1 and I'll fix the error ASAP.  Sorry about that my error.

**Comment by dmandala** [comment]
Fixed, changes pushed.  Thanks for noticing and questioning.  Again sorry for any inconvenience.
