### ISSUE TITLE
GPIO names different to spec

### ISSUE THREAD

**Issue by ukBaz** [96boards/96BoardsGPIO#8]
Slightly pedantic maybe ...

The [spec](https://www.96boards.org/wp-content/uploads/2015/02/96BoardsCESpecificationv1.0-EA1.pdf) uses (-) and the python bindings use underscores (_) 

So should:
`GPIO_A = GPIO.gpio_id('GPIO_A')`

be:
`GPIO_A = GPIO.gpio_id('GPIO-A')`

**Comment by doanac** [comment]
The underlying library actually supports both dash and underscore:

 https://github.com/96boards/96BoardsGPIO/blob/master/lib/gpio.c#L58

**Comment by ukBaz** [comment]
Thanks @doanac . You are correct, both underscore and dash work. I'll close the issue
